name: CI Trigger
on:
  push:
    tags:
      - '*'

jobs: 
  build:
    runs-on: ubuntu-20.04
    steps:
    # checkout sourcecode
    - name: Checkout code
      uses: actions/checkout@v3
    # echo commitid sourcecode
    - uses: benjlevesque/short-sha@v2.2
      id: short-sha
      with:
        length: 7
    - run: echo $SHA
      env:
        SHA: ${{ steps.short-sha.outputs.sha }}
    - run: echo $SHA
      env:
        SHA: ${{ env.SHA }}
      
    - name: Login to Docker Hub Private Repository
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: |
        docker pull thirapat12/thirapat12:${{ env.SHA }}
        docker tag thirapat12/thirapat12:${{ env.SHA }} thirapat12/thirapat12-develop:${{ env.SHA }}
        docker tag thirapat12/thirapat12:${{ env.SHA }} thirapat12/thirapat12-staging:${{ env.SHA }}
        docker tag thirapat12/thirapat12:${{ env.SHA }} thirapat12/thirapat12-master:${{ env.SHA }}
        echo ${{ env.SHA }} > version.txt
        ls -lrt
        cat version.txt


    